# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: dotnet test TestLib/TestLib.sln --logger trx --collect "Code coverage"
  displayName: 'Run test'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'